"""Rule edge-case tests for the Russian draughts engine.

Notation in ascii diagrams:
    .  empty
    w  white man      W  white king
    b  black man      B  black king

Row 0 = top of screen (black's home rank), row 7 = bottom (white's home rank).
"""

from __future__ import annotations

import pytest

from app.games.engine.board import (
    Board,
    Color,
    Piece,
    algebraic_to_square,
    square_to_algebraic,
)
from app.games.engine.moves import Move, apply_move, generate_legal_moves
from app.games.engine.rules import (
    REASON_NO_MOVES,
    REASON_NO_PIECES,
    REASON_PROGRESS_RULE,
    REASON_REPETITION,
    game_outcome,
)




def sq(s: str) -> tuple[int, int]:
    return algebraic_to_square(s)


def find_move(board: Board, *path: str) -> Move | None:
    """Find the legal move whose algebraic path matches the given squares."""
    target = tuple(sq(s) for s in path)
    for m in generate_legal_moves(board):
        if m.path == target:
            return m
    return None


def algebraic_moves(board: Board) -> set[str]:
    return {m.to_algebraic() for m in generate_legal_moves(board)}




def test_initial_position_layout():
    b = Board.initial()
    assert b.count(Color.WHITE) == (12, 0)
    assert b.count(Color.BLACK) == (12, 0)
    for (r, c), _ in b.iter_pieces():
        assert (r + c) % 2 == 1


def test_initial_position_has_seven_white_moves():
    b = Board.initial()
    moves = generate_legal_moves(b)
    assert len(moves) == 7  # four row-5 men: 1 + 2 + 2 + 2 advances
    assert all(not m.is_capture for m in moves)


def test_no_legal_move_after_white_loses_all_pieces():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ..b.....
        ........
        ........
        """,
        turn=Color.WHITE,
    )
    out = game_outcome(b)
    assert out.is_over and out.winner is Color.BLACK and out.reason == REASON_NO_PIECES




def test_mandatory_capture_prunes_quiet_moves():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ...b....
        ..w.....
        ........
        ........
        """,
        turn=Color.WHITE,
    )
    moves = generate_legal_moves(b)
    assert all(m.is_capture for m in moves)
    assert "c3xe5" in algebraic_moves(b)


def test_man_captures_backwards_in_russian_variant():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ...b....
        ..w.....
        ........
        ........
        """,
        turn=Color.BLACK,
    )
    moves = algebraic_moves(b)
    assert "d4xb2" in moves




def test_multi_jump_required_and_path_chosen():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ....b...
        ........
        ..b.....
        .w......
        ........
        """,
        turn=Color.WHITE,
    )
    moves = algebraic_moves(b)
    assert moves == {"b2xd4xf6"}, moves


def test_cannot_recapture_same_enemy():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ....b...
        ........
        ..b.....
        .w......
        ........
        """,
        turn=Color.WHITE,
    )
    captures = generate_legal_moves(b)
    for m in captures:
        assert len(set(m.captured)) == len(m.captured)




def test_man_promotes_mid_chain_and_continues_as_king():
    b = Board.from_ascii(
        """
        ........
        ..b.....
        ........
        ..b.....
        ........
        ..b.....
        ...w....
        ........
        """,
        turn=Color.WHITE,
    )
    move = find_move(b, "d2", "b4", "d6", "b8")
    assert move is not None, sorted(algebraic_moves(b))
    nb = apply_move(b, move)
    assert nb.get(sq("b8")) is Piece.WHITE_KING
    for s in ("c3", "c5", "c7"):
        assert nb.get(sq(s)) is Piece.EMPTY




def test_king_quiet_moves_slide_full_diagonal():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ........
        ........
        W.......
        """,
        turn=Color.WHITE,
    )
    moves = algebraic_moves(b)
    expected = {f"a1-{square_to_algebraic((7 - i, i))}" for i in range(1, 8)}
    assert moves == expected


def test_king_capture_lands_any_square_beyond_enemy():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ...b....
        ........
        ........
        W.......
        """,
        turn=Color.WHITE,
    )
    captures = algebraic_moves(b)
    assert captures == {f"a1x{land}" for land in ("e5", "f6", "g7", "h8")}


def test_king_blocked_by_own_piece_behind_enemy():
    b = Board.from_ascii(
        """
        ........
        ........
        .....w..
        ........
        ...b....
        ........
        ........
        W.......
        """,
        turn=Color.WHITE,
    )
    captures = algebraic_moves(b)
    assert captures == {"a1xe5"}


def test_king_captured_pieces_block_diagonals_during_chain():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ....b...
        ........
        ..b.....
        ........
        W.......
        """,
        turn=Color.WHITE,
    )
    moves = generate_legal_moves(b)
    for m in moves:
        assert m.captured[0] == sq("c3")
        assert len(set(m.captured)) == len(m.captured)
    two_caps = [m for m in moves if len(m.captured) == 2]
    assert two_caps, "expected at least one 2-capture chain"
    assert {m.captured[1] for m in two_caps} == {sq("e5")}




def test_quiet_promotion_at_end_of_move():
    b = Board.from_ascii(
        """
        ........
        w.......
        ........
        ........
        ........
        ........
        ........
        ........
        """,
        turn=Color.WHITE,
    )
    nb = apply_move(b, find_move(b, "a7", "b8"))
    assert nb.get(sq("b8")) is Piece.WHITE_KING




def test_no_legal_moves_is_loss_for_side_to_move():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ........
        .b......
        w.......
        """,
        turn=Color.WHITE,
    )
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ..b.....
        .b......
        w.......
        """,
        turn=Color.WHITE,
    )
    out = game_outcome(b)
    assert out.is_over and out.winner is Color.BLACK and out.reason == REASON_NO_MOVES




def test_threefold_repetition_draw():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ........
        ........
        W.....B.
        """,
        turn=Color.WHITE,
    )
    seq = [
        ("a1", "b2"),  # white
        ("g1", "h2"),  # black
        ("b2", "a1"),  # white
        ("h2", "g1"),  # black -> back to start (2nd occurrence of initial position)
        ("a1", "b2"),
        ("g1", "h2"),
        ("b2", "a1"),
        ("h2", "g1"),  # 3rd occurrence
    ]
    cur = b
    for src, dst in seq:
        m = find_move(cur, src, dst)
        assert m is not None, f"missing move {src}-{dst} from {sorted(algebraic_moves(cur))}"
        cur = apply_move(cur, m)
    out = game_outcome(cur)
    assert out.is_over and out.winner is None and out.reason == REASON_REPETITION


def test_progress_rule_draw_after_50_plies_of_king_dancing():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ........
        ........
        ........
        W.....B.
        """,
        turn=Color.WHITE,
    )
    b.plies_since_progress = 50
    out = game_outcome(b)
    assert out.is_over and out.winner is None and out.reason == REASON_PROGRESS_RULE




def test_apply_capture_removes_jumped_pieces():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ...b....
        ..w.....
        ........
        ........
        """,
        turn=Color.WHITE,
    )
    m = find_move(b, "c3", "e5")
    assert m is not None
    nb = apply_move(b, m)
    assert nb.get(sq("d4")) is Piece.EMPTY
    assert nb.get(sq("e5")) is Piece.WHITE_MAN
    assert nb.get(sq("c3")) is Piece.EMPTY
    assert nb.turn is Color.BLACK


def test_to_dict_roundtrip():
    b = Board.initial()
    moves = generate_legal_moves(b)
    nb = apply_move(b, moves[0])
    nb2 = Board.from_dict(nb.to_dict())
    assert nb2.to_ascii() == nb.to_ascii()
    assert nb2.turn is nb.turn




def test_player_may_choose_among_capture_paths():
    b = Board.from_ascii(
        """
        ........
        ........
        ........
        ........
        ...b.b..
        ..w.....
        ........
        ........
        """,
        turn=Color.WHITE,
    )
    captures = algebraic_moves(b)
    assert captures == {"c3xe5xg3"}
