"""Curated Russian-draughts puzzles for the Strategic Trainer.

Each puzzle is a starting position + the unique winning move sequence.
We keep them simple and verifiable from the engine so the analyser can
auto-validate solutions.
"""

from __future__ import annotations

from ..games.engine.board import Board, Color


def _pos(diagram: str, turn: Color) -> dict:
    return Board.from_ascii(diagram, turn=turn).to_dict()


PUZZLES = [
    {
        "theme": "single_capture",
        "difficulty": 1,
        "side_to_move": int(Color.WHITE),
        "description": "Найдите вынужденное взятие.",
        "position": _pos(
            """
            ........
            ........
            ........
            ........
            ...b....
            ..w.....
            ........
            ........
            """,
            Color.WHITE,
        ),
        "solution": [[[5, 2], [3, 4]]],
    },
    {
        "theme": "double_capture",
        "difficulty": 2,
        "side_to_move": int(Color.WHITE),
        "description": "Двойное взятие в один темп.",
        "position": _pos(
            """
            ........
            ........
            ........
            ....b...
            ........
            ..b.....
            .w......
            ........
            """,
            Color.WHITE,
        ),
        "solution": [[[6, 1], [4, 3], [2, 5]]],
    },
    {
        "theme": "triple_capture",
        "difficulty": 3,
        "side_to_move": int(Color.WHITE),
        "description": "Цепочка из трёх взятий с превращением.",
        "position": _pos(
            """
            ........
            ..b.....
            ........
            ..b.....
            ........
            ..b.....
            ...w....
            ........
            """,
            Color.WHITE,
        ),
        "solution": [[[6, 3], [4, 1], [2, 3], [0, 1]]],
    },
    {
        "theme": "king_fork",
        "difficulty": 4,
        "side_to_move": int(Color.WHITE),
        "description": "Дамка ловит обе чёрные шашки.",
        "position": _pos(
            """
            ........
            ........
            ........
            ....b...
            ........
            ..b.....
            ........
            W.......
            """,
            Color.WHITE,
        ),
        "solution": [
            [[7, 0], [4, 3]],
            [[7, 0], [3, 4]],
        ],
    },
    {
        "theme": "back_rank_promo",
        "difficulty": 2,
        "side_to_move": int(Color.WHITE),
        "description": "Простой ход в дамки.",
        "position": _pos(
            """
            ........
            w.......
            ........
            ........
            ........
            ........
            ........
            ........
            """,
            Color.WHITE,
        ),
        "solution": [[[1, 0], [0, 1]]],
    },
]
